spring:
  application:
    name: Blog-Agent

blog-agent:
  output-dir: blog-posts
  number-of-keywords: 5

embabel:
  agent:
    platform:
      models:
        openai:
          api-key: ${OPENAI_API_KEY}
    logging:
      personality: starwars

  models:
    default-llm: gpt-4o-mini
    llms:
      reviewer: gpt-5-mini

