spring:
  application:
    name: Blog-Agent

  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:server.json


blog-agent:
  output-dir: blog-posts
  number-of-keywords: 5




embabel:
  agent:
    platform:
      models:
        openai:
          api-key: ${OPENAI_API_KEY}
      tools:
        includes:
          tavily:
            description: "Search the web using Tavily AI search"
            provider: tavily-mcp
            tools:
              - tavily_search
              - tavily_extract
    logging:
      personality: starwars

  models:
    default-llm: gpt-4o-mini
    llms:
      reviewer: gpt-5-mini

